# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-22 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
